# Northwind Database Practice
This notebook contains SQL practices from the Northwind Database. Northwind is a database sample that is shipped along with the Microsoft Access application. This database has 8 tables, namely Customers, Employees, Shippers, Orders, OrderDetail, Products, Suppliers, and Categories. I obtained all the practice questions from https://www.sql-practice.com/. Thanks to [JP White](https://github.com/jpwhite3), I can access this database easily in the form of SQLite3. The database can be accessed at this [link](https://github.com/jpwhite3/northwind-SQLite3/blob/main/dist/northwind.db).

In [1]:
# import libraries
import pandas as pd
import sqlite3

In [2]:
#!pip install ipython-sql

In [3]:
db_url = 'https://github.com/jpwhite3/northwind-SQLite3/raw/main/dist/northwind.db'
cnn = sqlite3.connect('northwind.db')

In [4]:
%load_ext sql

In [5]:
%sql sqlite:///northwind.db

In [6]:
%%sql
--Show the CategoryName and Description from the Categories table sorted by CategoryName. (EASY)

SELECT CategoryName, Description
FROM Categories
ORDER BY CategoryName

 * sqlite:///northwind.db
Done.

[('Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
 ('Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
 ('Confections', 'Desserts, candies, and sweet breads'),
 ('Dairy Products', 'Cheeses'),
 ('Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
 ('Meat/Poultry', 'Prepared meats'),
 ('Produce', 'Dried fruit and bean curd'),
 ('Seafood', 'Seaweed and fish')]

In [7]:
%%sql
--Show all the ContactName, Address, City of all Customers which are not from 'Germany', 'Mexico', 'Spain' (EASY)

SELECT ContactName, Address, City
FROM Customers
WHERE Country != 'Germany' AND Country != 'Mexico' AND Country != 'Spain'

 * sqlite:///northwind.db
Done.

[('Thomas Hardy', '120 Hanover Sq.', 'London'),
 ('Christina Berglund', 'Berguvsvägen  8', 'Luleå'),
 ('Frédérique Citeaux', '24, place Kléber', 'Strasbourg'),
 ('Laurence Lebihan', '12, rue des Bouchers', 'Marseille'),
 ('Elizabeth Lincoln', '23 Tsawassen Blvd.', 'Tsawassen'),
 ('Victoria Ashworth', 'Fauntleroy Circus', 'London'),
 ('Patricio Simpson', 'Cerrito 333', 'Buenos Aires'),
 ('Yang Wang', 'Hauptstr. 29', 'Bern'),
 ('Pedro Afonso', 'Av. dos Lusíadas, 23', 'Sao Paulo'),
 ('Elizabeth Brown', 'Berkeley Gardens 12  Brewery', 'London'),
 ('Janine Labrune', '67, rue des Cinquante Otages', 'Nantes'),
 ('Ann Devon', '35 King George', 'London'),
 ('Roland Mendel', 'Kirchgasse 6', 'Graz'),
 ('Aria Cruz', 'Rua Orós, 92', 'Sao Paulo'),
 ('Martine Rancé', '184, chaussée de Tournai', 'Lille'),
 ('Maria Larsson', 'Åkergatan 24', 'Bräcke'),
 ('Carine Schmitt', '54, rue Royale', 'Nantes'),
 ('Paolo Accorti', 'Via Monte Bianco 34', 'Torino'),
 ('Lino Rodriguez', 'Jardim das rosas n. 32', 'Lisboa'),
 ('André Fonseca', 'Av. Brasil, 442', 'Campinas'),
 ('Howard Snyder', '2732 Baker Blvd.', 'Eugene'),
 ('Manuel Pereira', '5ª Ave. Los Palos Grandes', 'Caracas'),
 ('Mario Pontes', 'Rua do Paço, 67', 'Rio de Janeiro'),
 ('Carlos Hernández', 'Carrera 22 con Ave. Carlos Soublette #8-35', 'San Cristóbal'),
 ('Yoshi Latimer', 'City Center Plaza 516 Main St.', 'Elgin'),
 ('Patricia McKenna', '8 Johnstown Road', 'Cork'),
 ('Helen Bennett', 'Garden House Crowther Way', 'Cowes'),
 ('Daniel Tonini', "67, avenue de l'Europe", 'Versailles'),
 ('Annette Roulet', '1 rue Alsace-Lorraine', 'Toulouse'),
 ('Yoshi Tannamuri', '1900 Oak St.', 'Vancouver'),
 ('John Steel', '12 Orchestra Terrace', 'Walla Walla'),
 ('Jaime Yorres', '87 Polk St. Suite 5', 'San Francisco'),
 ('Carlos González', 'Carrera 52 con Ave. Bolívar #65-98 Llano Largo', 'Barquisimeto'),
 ('Felipe Izquierdo', 'Ave. 5 de Mayo Porlamar', 'I. de Margarita'),
 ('Fran Wilson', '89 Chiaroscuro Rd.', 'Portland'),
 ('Giovanni Rovelli', 'Via Ludovico il Moro 22', 'Bergamo'),
 ('Catherine Dewey', 'Rue Joseph-Bens 532', 'Bruxelles'),
 ('Jean Fresnière', '43 rue St. Laurent', 'Montréal'),
 ('Simon Crowther', 'South House 300 Queensbridge', 'London'),
 ('Yvonne Moncada', 'Ing. Gustavo Moncada 8585 Piso 20-A', 'Buenos Aires'),
 ('Rene Phillips', '2743 Bering St.', 'Anchorage'),
 ('Marie Bertrand', '265, boulevard Charonne', 'Paris'),
 ('Georg Pipps', 'Geislweg 14', 'Salzburg'),
 ('Isabel de Castro', 'Estrada da saúde n. 58', 'Lisboa'),
 ('Bernardo Batista', 'Rua da Panificadora, 12', 'Rio de Janeiro'),
 ('Lúcia Carvalho', 'Alameda dos Canàrios, 891', 'Sao Paulo'),
 ('Sergio Gutiérrez', 'Av. del Libertador 900', 'Buenos Aires'),
 ('Paula Wilson', '2817 Milton Dr.', 'Albuquerque'),
 ('Maurizio Moroni', 'Strada Provinciale 124', 'Reggio Emilia'),
 ('Janete Limeira', 'Av. Copacabana, 267', 'Rio de Janeiro'),
 ('Michael Holz', 'Grenzacherweg 237', 'Genève'),
 ('Jonas Bergulfsen', 'Erling Skakkes gate 78', 'Stavern'),
 ('Jose Pavarotti', '187 Suffolk Ln.', 'Boise'),
 ('Hari Kumar', '90 Wadhurst Rd.', 'London'),
 ('Jytte Petersen', 'Vinbæltet 34', 'Kobenhavn'),
 ('Dominique Perrier', '25, rue Lauriston', 'Paris'),
 ('Art Braunschweiger', 'P.O. Box 555', 'Lander'),
 ('Pascale Cartrain', 'Boulevard Tirou, 255', 'Charleroi'),
 ('Liz Nixon', '89 Jefferson Way Suite 2', 'Portland'),
 ('Liu Wong', '55 Grizzly Peak Rd.', 'Butte'),
 ('Anabela Domingues', 'Av. Inês de Castro, 414', 'Sao Paulo'),
 ('Helvetius Nagy', '722 DaVinci Blvd.', 'Kirkland'),
 ('Palle Ibsen', 'Smagsloget 45', 'Århus'),
 ('Mary Saveley', '2, rue du Commerce', 'Lyon'),
 ('Paul Henriot', "59 rue de l'Abbaye", 'Reims'),
 ('Pirkko Koskitalo', 'Torikatu 38', 'Oulu'),
 ('Paula Parente', 'Rua do Mercado, 12', 'Resende'),
 ('Karl Jablonski', '305 - 14th Ave. S. Suite 3B', 'Seattle'),
 ('Matti Karttunen', 'Keskuskatu 45', 'Helsinki'),
 ('Zbyszek Piestrzeniewicz', 'ul. Filtrowa 68', 'Warszawa')]

In [8]:
%%sql
--Show OrderDate, ShippedDate, CustomerID, Freight of all Orders placed on 2018 Feb 26 (EASY)

SELECT OrderDate, ShippedDate, CustomerID, Freight
FROM Orders
WHERE OrderDate = '2018-02-26'

 * sqlite:///northwind.db
Done.

[('2018-02-26', '2018-03-06', 'REGGC', 18.5),
 ('2018-02-26', '2018-03-10', 'SANTG', 18),
 ('2018-02-26', '2018-03-04', 'WILMK', 16.75),
 ('2018-02-26', '2018-03-05', 'GODOS', 19.25),
 ('2018-02-26', '2018-03-18', 'HUNGO', 35),
 ('2018-02-26', '2018-03-04', 'QUEEN', 31.25)]

In [9]:
%%sql
--Show the EmployeeID, OrderID, CustomerID, RequiredDate, ShippedDate from all Orders shipped later than the required date (EASY)

SELECT EmployeeID, OrderID, CustomerID, RequiredDate, ShippedDate
FROM Orders
WHERE ShippedDate > RequiredDate
--LIMIT 10

 * sqlite:///northwind.db
Done.

[(6, 10264, 'FOLKO', '2016-08-21', '2016-08-23'),
 (6, 10271, 'SPLIR', '2016-08-29', '2016-08-30'),
 (2, 10280, 'BERGS', '2016-09-11', '2016-09-12'),
 (4, 10302, 'SUPRD', '2016-10-08', '2016-10-09'),
 (3, 10309, 'HUNGO', '2016-10-17', '2016-10-23'),
 (5, 10320, 'WARTH', '2016-10-17', '2016-10-18'),
 (8, 10380, 'HUNGO', '2017-01-09', '2017-01-16'),
 (6, 10423, 'GOURL', '2017-02-06', '2017-02-24'),
 (4, 10427, 'PICCO', '2017-02-24', '2017-03-03'),
 (3, 10433, 'PRINI', '2017-03-03', '2017-03-04')]

In [10]:
%%sql
--Show all the even numbered OrderID from the Orders table (EASY)

SELECT OrderID
FROM Orders
WHERE OrderID % 2 = 0
--LIMIT 10

 * sqlite:///northwind.db
Done.

[(10248,),
 (10250,),
 (10252,),
 (10254,),
 (10256,),
 (10258,),
 (10260,),
 (10262,),
 (10264,),
 (10266,)]

In [11]:
%%sql
--Show the City, CompanyName, ContactName of all Customers from cities which contains the letter 'L' in the City name, sorted by ContactName (EASY)

SELECT City, CompanyName, ContactName
FROM Customers
WHERE City LIKE '%L%'
ORDER BY ContactName

 * sqlite:///northwind.db
Done.

[('Leipzig', 'Morgenstern Gesundkost', 'Alexander Feuer'),
 ('Sao Paulo', 'Tradição Hipermercados', 'Anabela Domingues'),
 ('London', 'Eastern Connection', 'Ann Devon'),
 ('Toulouse', "La maison d'Asie", 'Annette Roulet'),
 ('Sao Paulo', 'Familia Arquibaldo', 'Aria Cruz'),
 ('Lander', 'Split Rail Beer & Ale', 'Art Braunschweiger'),
 ('San Cristóbal', 'HILARION-Abastos', 'Carlos Hernández'),
 ('Bruxelles', 'Maison Dewey', 'Catherine Dewey'),
 ('Luleå', 'Berglunds snabbköp', 'Christina Berglund'),
 ('Versailles', "La corne d'abondance", 'Daniel Tonini'),
 ('Barcelona', 'Galería del gastrónomo', 'Eduardo Saavedra'),
 ('London', 'Consolidated Holdings', 'Elizabeth Brown'),
 ('Portland', 'Lonesome Pine Restaurant', 'Fran Wilson'),
 ('Salzburg', 'Piccolo und mehr', 'Georg Pipps'),
 ('London', 'Seven Seas Imports', 'Hari Kumar'),
 ('Kirkland', "Trail's Head Gourmet Provisioners", 'Helvetius Nagy'),
 ('Köln', 'Ottilies Käseladen', 'Henriette Pfalzheim'),
 ('Cunewalde', 'QUICK-Stop', 'Horst Kloss'),
 ('Lisboa', 'Princesa Isabel Vinhos', 'Isabel de Castro'),
 ('Montréal', 'Mère Paillarde', 'Jean Fresnière'),
 ('Walla Walla', 'Lazy K Kountry Store', 'John Steel'),
 ('Sevilla', 'Godos Cocina Típica', 'José Pedro Freyre'),
 ('Seattle', 'White Clover Markets', 'Karl Jablonski'),
 ('Marseille', "Bon app'", 'Laurence Lebihan'),
 ('Lisboa', 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez'),
 ('Portland', 'The Big Cheese', 'Liz Nixon'),
 ('Sao Paulo', 'Queen Cozinha', 'Lúcia Carvalho'),
 ('Berlin', 'Alfreds Futterkiste', 'Maria Anders'),
 ('Lille', 'Folies gourmandes', 'Martine Rancé'),
 ('Lyon', 'Victuailles en stock', 'Mary Saveley'),
 ('Helsinki', 'Wilman Kala', 'Matti Karttunen'),
 ('Reggio Emilia', 'Reggiani Caseifici', 'Maurizio Moroni'),
 ('Charleroi', 'Suprêmes délices', 'Pascale Cartrain'),
 ('Albuquerque', 'Rattlesnake Canyon Grocery', 'Paula Wilson'),
 ('Sao Paulo', 'Comércio Mineiro', 'Pedro Afonso'),
 ('Oulu', 'Wartian Herkku', 'Pirkko Koskitalo'),
 ('London', 'North/South', 'Simon Crowther'),
 ('London', 'Around the Horn', 'Thomas Hardy'),
 ('London', "B's Beverages", 'Victoria Ashworth'),
 ('Elgin', 'Hungry Coyote Import Store', 'Yoshi Latimer')]

In [12]:
%%sql
--Show the CompanyName, ContactName, Fax number of all Customers that has a Fax number. (not null) (EASY)

SELECT CompanyName, ContactName, Fax
FROM Customers
WHERE Fax IS NOT NULL

 * sqlite:///northwind.db
Done.

[('Alfreds Futterkiste', 'Maria Anders', '030-0076545'),
 ('Ana Trujillo Emparedados y helados', 'Ana Trujillo', '(5) 555-3745'),
 ('Around the Horn', 'Thomas Hardy', '(171) 555-6750'),
 ('Berglunds snabbköp', 'Christina Berglund', '0921-12 34 67'),
 ('Blauer See Delikatessen', 'Hanna Moos', '0621-08924'),
 ('Blondesddsl père et fils', 'Frédérique Citeaux', '88.60.15.32'),
 ('Bólido Comidas preparadas', 'Martín Sommer', '(91) 555 91 99'),
 ("Bon app'", 'Laurence Lebihan', '91.24.45.41'),
 ('Bottom-Dollar Markets', 'Elizabeth Lincoln', '(604) 555-3745'),
 ('Cactus Comidas para llevar', 'Patricio Simpson', '(1) 135-4892'),
 ('Centro comercial Moctezuma', 'Francisco Chang', '(5) 555-7293'),
 ('Consolidated Holdings', 'Elizabeth Brown', '(171) 555-9199'),
 ('Drachenblut Delikatessen', 'Sven Ottlieb', '0241-059428'),
 ('Du monde entier', 'Janine Labrune', '40.67.89.89'),
 ('Eastern Connection', 'Ann Devon', '(171) 555-3373'),
 ('Ernst Handel', 'Roland Mendel', '7675-3426'),
 ('FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', '(91) 555 55 93'),
 ('Folies gourmandes', 'Martine Rancé', '20.16.10.17'),
 ('Frankenversand', 'Peter Franken', '089-0877451'),
 ('France restauration', 'Carine Schmitt', '40.32.21.20'),
 ('Franchi S.p.A.', 'Paolo Accorti', '011-4988261'),
 ('Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', '(1) 354-2535'),
 ('Galería del gastrónomo', 'Eduardo Saavedra', '(93) 203 4561'),
 ('GROSELLA-Restaurante', 'Manuel Pereira', '(2) 283-3397'),
 ('Hanari Carnes', 'Mario Pontes', '(21) 555-8765'),
 ('HILARION-Abastos', 'Carlos Hernández', '(5) 555-1948'),
 ('Hungry Coyote Import Store', 'Yoshi Latimer', '(503) 555-2376'),
 ('Hungry Owl All-Night Grocers', 'Patricia McKenna', '2967 3333'),
 ("La corne d'abondance", 'Daniel Tonini', '30.59.85.11'),
 ("La maison d'Asie", 'Annette Roulet', '61.77.61.11'),
 ('Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', '(604) 555-7293'),
 ('Lazy K Kountry Store', 'John Steel', '(509) 555-6221'),
 ('Lehmanns Marktstand', 'Renate Messner', '069-0245874'),
 ('LILA-Supermercado', 'Carlos González', '(9) 331-7256'),
 ('LINO-Delicateses', 'Felipe Izquierdo', '(8) 34-93-93'),
 ('Lonesome Pine Restaurant', 'Fran Wilson', '(503) 555-9646'),
 ('Magazzini Alimentari Riuniti', 'Giovanni Rovelli', '035-640231'),
 ('Maison Dewey', 'Catherine Dewey', '(02) 201 24 68'),
 ('Mère Paillarde', 'Jean Fresnière', '(514) 555-8055'),
 ('North/South', 'Simon Crowther', '(171) 555-2530'),
 ('Océano Atlántico Ltda.', 'Yvonne Moncada', '(1) 135-5535'),
 ('Old World Delicatessen', 'Rene Phillips', '(907) 555-2880'),
 ('Ottilies Käseladen', 'Henriette Pfalzheim', '0221-0765721'),
 ('Paris spécialités', 'Marie Bertrand', '(1) 42.34.22.77'),
 ('Pericles Comidas clásicas', 'Guillermo Fernández', '(5) 545-3745'),
 ('Piccolo und mehr', 'Georg Pipps', '6562-9723'),
 ('Que Delícia', 'Bernardo Batista', '(21) 555-4545'),
 ('Rancho grande', 'Sergio Gutiérrez', '(1) 123-5556'),
 ('Rattlesnake Canyon Grocery', 'Paula Wilson', '(505) 555-3620'),
 ('Reggiani Caseifici', 'Maurizio Moroni', '0522-556722'),
 ('Romero y tomillo', 'Alejandra Camino', '(91) 745 6210'),
 ('Santé Gourmet', 'Jonas Bergulfsen', '07-98 92 47'),
 ('Seven Seas Imports', 'Hari Kumar', '(171) 555-5646'),
 ('Simons bistro', 'Jytte Petersen', '31 13 35 57'),
 ('Spécialités du monde', 'Dominique Perrier', '(1) 47.55.60.20'),
 ('Split Rail Beer & Ale', 'Art Braunschweiger', '(307) 555-6525'),
 ('Suprêmes délices', 'Pascale Cartrain', '(071) 23 67 22 21'),
 ('The Cracker Box', 'Liu Wong', '(406) 555-8083'),
 ('Toms Spezialitäten', 'Karin Josephs', '0251-035695'),
 ('Tradição Hipermercados', 'Anabela Domingues', '(11) 555-2168'),
 ("Trail's Head Gourmet Provisioners", 'Helvetius Nagy', '(206) 555-2174'),
 ('Vaffeljernet', 'Palle Ibsen', '86 22 33 44'),
 ('Victuailles en stock', 'Mary Saveley', '78.32.54.87'),
 ('Vins et alcools Chevalier', 'Paul Henriot', '26.47.15.11'),
 ('Die Wandernde Kuh', 'Rita Müller', '0711-035428'),
 ('Wartian Herkku', 'Pirkko Koskitalo', '981-443655'),
 ('White Clover Markets', 'Karl Jablonski', '(206) 555-4115'),
 ('Wilman Kala', 'Matti Karttunen', '90-224 8858'),
 ('Wolski  Zajazd', 'Zbyszek Piestrzeniewicz', '(26) 642-7012')]

In [13]:
%%sql
--Show the FirstName, LastName. HireDate of the most recently hired employee. (EASY)

SELECT FirstName, LastName, HireDate
FROM Employees
order by HireDate DESC
LIMIT 1

 * sqlite:///northwind.db
Done.

[('Anne', 'Dodsworth', '2014-11-15')]

In [14]:
%%sql
--Show the average unit price rounded to 2 decimal places, the total units in stock, total Discontinued Products from the Products table. (EASY)

SELECT 
    ROUND(avg(UnitPrice),2) AS AveragePrice,
    SUM(UnitsInStock) AS TotalStock,
    SUM(Discontinued) AS TotalDiscontinued
FROM Products

 * sqlite:///northwind.db
Done.

[(28.87, 3119, 8)]

In [15]:
%%sql
--Show the ProductName, CompanyName, CategoryName from the Products, Suppliers, and Categories table (MEDIUM)

SELECT p.ProductName, s.CompanyName, c.CategoryName
FROM Products p
JOIN Suppliers s
    ON p.SupplierID = s.SupplierID
JOIN Categories c
    ON p.CategoryID = c.CategoryID

 * sqlite:///northwind.db
Done.

[('Chai', 'Exotic Liquids', 'Beverages'),
 ('Chang', 'Exotic Liquids', 'Beverages'),
 ('Aniseed Syrup', 'Exotic Liquids', 'Condiments'),
 ("Chef Anton's Cajun Seasoning", 'New Orleans Cajun Delights', 'Condiments'),
 ("Chef Anton's Gumbo Mix", 'New Orleans Cajun Delights', 'Condiments'),
 ("Grandma's Boysenberry Spread", "Grandma Kelly's Homestead", 'Condiments'),
 ("Uncle Bob's Organic Dried Pears", "Grandma Kelly's Homestead", 'Produce'),
 ('Northwoods Cranberry Sauce', "Grandma Kelly's Homestead", 'Condiments'),
 ('Mishi Kobe Niku', 'Tokyo Traders', 'Meat/Poultry'),
 ('Ikura', 'Tokyo Traders', 'Seafood'),
 ('Queso Cabrales', "Cooperativa de Quesos 'Las Cabras'", 'Dairy Products'),
 ('Queso Manchego La Pastora', "Cooperativa de Quesos 'Las Cabras'", 'Dairy Products'),
 ('Konbu', "Mayumi's", 'Seafood'),
 ('Tofu', "Mayumi's", 'Produce'),
 ('Genen Shouyu', "Mayumi's", 'Condiments'),
 ('Pavlova', 'Pavlova, Ltd.', 'Confections'),
 ('Alice Mutton', 'Pavlova, Ltd.', 'Meat/Poultry'),
 ('Carnarvon Tigers', 'Pavlova, Ltd.', 'Seafood'),
 ('Teatime Chocolate Biscuits', 'Specialty Biscuits, Ltd.', 'Confections'),
 ("Sir Rodney's Marmalade", 'Specialty Biscuits, Ltd.', 'Confections'),
 ("Sir Rodney's Scones", 'Specialty Biscuits, Ltd.', 'Confections'),
 ("Gustaf's Knäckebröd", 'PB Knäckebröd AB', 'Grains/Cereals'),
 ('Tunnbröd', 'PB Knäckebröd AB', 'Grains/Cereals'),
 ('Guaraná Fantástica', 'Refrescos Americanas LTDA', 'Beverages'),
 ('NuNuCa Nuß-Nougat-Creme', 'Heli Süßwaren GmbH & Co. KG', 'Confections'),
 ('Gumbär Gummibärchen', 'Heli Süßwaren GmbH & Co. KG', 'Confections'),
 ('Schoggi Schokolade', 'Heli Süßwaren GmbH & Co. KG', 'Confections'),
 ('Rössle Sauerkraut', 'Plutzer Lebensmittelgroßmärkte AG', 'Produce'),
 ('Thüringer Rostbratwurst', 'Plutzer Lebensmittelgroßmärkte AG', 'Meat/Poultry'),
 ('Nord-Ost Matjeshering', 'Nord-Ost-Fisch Handelsgesellschaft mbH', 'Seafood'),
 ('Gorgonzola Telino', 'Formaggi Fortini s.r.l.', 'Dairy Products'),
 ('Mascarpone Fabioli', 'Formaggi Fortini s.r.l.', 'Dairy Products'),
 ('Geitost', 'Norske Meierier', 'Dairy Products'),
 ('Sasquatch Ale', 'Bigfoot Breweries', 'Beverages'),
 ('Steeleye Stout', 'Bigfoot Breweries', 'Beverages'),
 ('Inlagd Sill', 'Svensk Sjöföda AB', 'Seafood'),
 ('Gravad lax', 'Svensk Sjöföda AB', 'Seafood'),
 ('Côte de Blaye', 'Aux joyeux ecclésiastiques', 'Beverages'),
 ('Chartreuse verte', 'Aux joyeux ecclésiastiques', 'Beverages'),
 ('Boston Crab Meat', 'New England Seafood Cannery', 'Seafood'),
 ("Jack's New England Clam Chowder", 'New England Seafood Cannery', 'Seafood'),
 ('Singaporean Hokkien Fried Mee', 'Leka Trading', 'Grains/Cereals'),
 ('Ipoh Coffee', 'Leka Trading', 'Beverages'),
 ('Gula Malacca', 'Leka Trading', 'Condiments'),
 ('Rogede sild', 'Lyngbysild', 'Seafood'),
 ('Spegesild', 'Lyngbysild', 'Seafood'),
 ('Zaanse koeken', 'Zaanse Snoepfabriek', 'Confections'),
 ('Chocolade', 'Zaanse Snoepfabriek', 'Confections'),
 ('Maxilaku', 'Karkki Oy', 'Confections'),
 ('Valkoinen suklaa', 'Karkki Oy', 'Confections'),
 ('Manjimup Dried Apples', "G'day, Mate", 'Produce'),
 ('Filo Mix', "G'day, Mate", 'Grains/Cereals'),
 ('Perth Pasties', "G'day, Mate", 'Meat/Poultry'),
 ('Tourtière', 'Ma Maison', 'Meat/Poultry'),
 ('Pâté chinois', 'Ma Maison', 'Meat/Poultry'),
 ('Gnocchi di nonna Alice', 'Pasta Buttini s.r.l.', 'Grains/Cereals'),
 ('Ravioli Angelo', 'Pasta Buttini s.r.l.', 'Grains/Cereals'),
 ('Escargots de Bourgogne', 'Escargots Nouveaux', 'Seafood'),
 ('Raclette Courdavault', 'Gai pâturage', 'Dairy Products'),
 ('Camembert Pierrot', 'Gai pâturage', 'Dairy Products'),
 ("Sirop d'érable", "Forêts d'érables", 'Condiments'),
 ('Tarte au sucre', "Forêts d'érables", 'Confections'),
 ('Vegie-spread', 'Pavlova, Ltd.', 'Condiments'),
 ('Wimmers gute Semmelknödel', 'Plutzer Lebensmittelgroßmärkte AG', 'Grains/Cereals'),
 ('Louisiana Fiery Hot Pepper Sauce', 'New Orleans Cajun Delights', 'Condiments'),
 ('Louisiana Hot Spiced Okra', 'New Orleans Cajun Delights', 'Condiments'),
 ('Laughing Lumberjack Lager', 'Bigfoot Breweries', 'Beverages'),
 ('Scottish Longbreads', 'Specialty Biscuits, Ltd.', 'Confections'),
 ('Gudbrandsdalsost', 'Norske Meierier', 'Dairy Products'),
 ('Outback Lager', 'Pavlova, Ltd.', 'Beverages'),
 ('Flotemysost', 'Norske Meierier', 'Dairy Products'),
 ('Mozzarella di Giovanni', 'Formaggi Fortini s.r.l.', 'Dairy Products'),
 ('Röd Kaviar', 'Svensk Sjöföda AB', 'Seafood'),
 ('Longlife Tofu', 'Tokyo Traders', 'Produce'),
 ('Rhönbräu Klosterbier', 'Plutzer Lebensmittelgroßmärkte AG', 'Beverages'),
 ('Lakkalikööri', 'Karkki Oy', 'Beverages'),
 ('Original Frankfurter grüne Soße', 'Plutzer Lebensmittelgroßmärkte AG', 'Condiments')]

In [16]:
%%sql
--Show the CategoryName and the average product unit price for each category rounded to 2 decimal places. (MEDIUM)

SELECT c.CategoryName, round(avg(p.UnitPrice), 2) AS average_price
FROM Categories c
JOIN Products p
ON c.CategoryID = p.CategoryID
group by CategoryName

 * sqlite:///northwind.db
Done.

[('Beverages', 37.98),
 ('Condiments', 23.06),
 ('Confections', 25.16),
 ('Dairy Products', 28.73),
 ('Grains/Cereals', 20.25),
 ('Meat/Poultry', 54.01),
 ('Produce', 32.37),
 ('Seafood', 20.68)]

In [17]:
%%sql
--Show the City, CompanyName, ContactName from the Customers and Suppliers table merged together.
--Create a column which contains 'Customers' or 'Suppliers' depending on the table it came from. (MEDIUM)

SELECT City, CompanyName, ContactName, 'Customers' AS Relationship
FROM Customers
UNION ALL
SELECT City, CompanyName, ContactName, 'Suppliers' AS Relationship
FROM Suppliers
--LIMIT 10

 * sqlite:///northwind.db
Done.

[('Berlin', 'Alfreds Futterkiste', 'Maria Anders', 'Customers'),
 ('México D.F.', 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Customers'),
 ('México D.F.', 'Antonio Moreno Taquería', 'Antonio Moreno', 'Customers'),
 ('London', 'Around the Horn', 'Thomas Hardy', 'Customers'),
 ('Luleå', 'Berglunds snabbköp', 'Christina Berglund', 'Customers'),
 ('Mannheim', 'Blauer See Delikatessen', 'Hanna Moos', 'Customers'),
 ('Strasbourg', 'Blondesddsl père et fils', 'Frédérique Citeaux', 'Customers'),
 ('Madrid', 'Bólido Comidas preparadas', 'Martín Sommer', 'Customers'),
 ('Marseille', "Bon app'", 'Laurence Lebihan', 'Customers'),
 ('Tsawassen', 'Bottom-Dollar Markets', 'Elizabeth Lincoln', 'Customers')]

In [18]:
%%sql
--Show the employee's FirstName and LastName, a "num_orders" column with a count of the Orders taken, and a column called "Shipped" that displays "On Time" if the order ShippedDate is less or equal to the RequiredDate, "Late" if the order shipped late.
--Order by employee LastName, then by FirstName, and then descending by number of Orders. (HARD)

SELECT 
	e.FirstName,
    e.LastName,
    COUNT(*) AS NumOrders,
    CASE
    	WHEN o.ShippedDate <= o.RequiredDate THEN 'On Time'
    	ELSE 'Late'
    END AS Shipped
FROM Employees e
JOIN Orders o
	ON e.EmployeeID = o.EmployeeID
group by e.FirstName, e.LastName, Shipped
order by e.LastName, e.FirstName, NumOrders DESC

 * sqlite:///northwind.db
Done.

[('Steven', 'Buchanan', 1405, 'On Time'),
 ('Steven', 'Buchanan', 399, 'Late'),
 ('Laura', 'Callahan', 1364, 'On Time'),
 ('Laura', 'Callahan', 434, 'Late'),
 ('Nancy', 'Davolio', 1437, 'On Time'),
 ('Nancy', 'Davolio', 409, 'Late'),
 ('Anne', 'Dodsworth', 1336, 'On Time'),
 ('Anne', 'Dodsworth', 430, 'Late'),
 ('Andrew', 'Fuller', 1387, 'On Time'),
 ('Andrew', 'Fuller', 384, 'Late'),
 ('Robert', 'King', 1351, 'On Time'),
 ('Robert', 'King', 438, 'Late'),
 ('Janet', 'Leverling', 1407, 'On Time'),
 ('Janet', 'Leverling', 439, 'Late'),
 ('Margaret', 'Peacock', 1483, 'On Time'),
 ('Margaret', 'Peacock', 425, 'Late'),
 ('Michael', 'Suyama', 1336, 'On Time'),
 ('Michael', 'Suyama', 418, 'Late')]